module types_and_kinds 
    IMPLICIT NONE 
    INTEGER, PARAMETER :: RK = SELECTED_REAL_KIND(15, 307)
    INTEGER, PARAMETER :: IK = SELECTED_INT_KIND(8)
    ! INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(15, 307)
    ! INTEGER, PARAMETER :: SP = SELECTED_REAL_KIND(6, 37)
    ! INTEGER, PARAMETER :: IP = SELECTED_INT_KIND(4)
    ! INTEGER, PARAMETER :: LP = SELECTED_LOGICAL_KIND(4)
    ! INTEGER, PARAMETER :: CP = SELECTED_CHAR_KIND(1)
    
end module types_and_kinds